config/routes.rb
Rails.application.routes.draw do

  resources :projects
  resources :projects, only: [:show] do
    resources :scenes, only: [:index, :destroy, :update, :create, :show, :edit] do
      resources :decisions, only: [:create, :update, :destroy]
    end
  end

  devise_for :users
  root to: 'pages#home'

  get 'profile' => "pages#profile", as: "profile"

  get '/projects/:id/owner_workspace', to: 'projects#owner_workspace', as: "project_owner_work"
  get '/projects/:id/elaborate_scenes', to: 'projects#elaborate_scenes', as: "project_elaborate_scenes"
  get '/projects/:id/play', to: 'projects#play', as: "project_play"


  get '/projects/:project_id/scenes/:id/json', to: 'scenes#show_json', as: "project_scene_show_json"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/decision.rb
class Decision < ApplicationRecord
  belongs_to :scene
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :scenes, dependent: :destroy
end

app/models/scene.rb
class Scene < ApplicationRecord
  belongs_to :project
  has_many :decisions, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_many :projects
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/decisions_controller.rb
class DecisionsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_decision, only: [:update, :destroy]

  def new
  end

  def create
    @decision = Decision.create(decision_params)
    # set_next
    # set_scene
    # @decision.scene = @scene
    # @decision.next = @next
    if @decision.save
      puts "decision created"
    else
      puts "decision creation failure"
    end
  end

  def edit
  end

  def update
    if @decision.update(decision_params)
      puts "updated decision"
    else
      puts "decision update failure"
    end
  end

  def index
  end

  def show
  end

  def destroy
    @decision.destroy
  end

  private
  def set_scene
    @scene = Scene.find(params[:scene_id])
  end
  def set_next
    @next = Scene.find(params[:next_id])
  end
  def set_decision
    @decision = Decision.find(params[:id])
  end
  def decision_params
    params.require(:decision).permit(:description, :scene_id, :previous_editor_id, :next_id, :next_editor_id, :p1, :p2, :p3, :p4, :p5, :p6, :p7, :p8)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @projects = Project.all
  end

  def profile
    @projects = current_user.projects
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_project, only: [:show, :edit, :update, :destroy, :owner_workspace, :elaborate_scenes, :play]
  before_action :authenticate_user!, only: [:new, :create, :owner_workspace, :elaborate_scenes, :update, :edit, :destroy]

  def new
    @project = Project.new
  end

  def create
    @project = Project.create(project_params)
    @project.user = current_user if current_user
    if @project.save
      redirect_to project_path(@project)
    else
      render :new
    end
  end

  def show
  end

  def play
  end

  def owner_workspace
  end

  def elaborate_scenes
  end

  def update
    if @project.update(project_params)
      render :show
    else
      render :edit
    end
  end

  def edit
  end

  def destroy
    @project.scenes.each do |s|
      s.destroy
    end
    @project.destroy
    redirect_back(fallback_location: root_path)
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :description, :user_id, :published)
  end
end

app/controllers/scenes_controller.rb
class ScenesController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_scene, only: [:show, :edit, :update, :destroy, :show_json]
  before_action :authenticate_user!, only: [:create, :edit, :update, :destroy]

  def create
    @scene = Scene.create(scene_params)
    @p = Project.find(params["project_id"])
    @scene.project = @p
    if @scene.save
      puts "scene created"
      # redirect_to project_owner_work_path(@p)
    else
      puts "scene not created"
      # render :new
    end
  end

  def edit
    puts params
  end

  def update
    if @scene.update(scene_params)
      puts "scene updated"
    else
      puts "scene update failure"
    end
  end

  def index
    @p = Project.find(params["project_id"])
    @scenes = @p.scenes
  end

  def show
  end

  def show_json
  end

  def destroy
    @scene.decisions.each do |d|
      d.destroy
    end
    @scene.destroy
  end

  private
  def set_scene
    @scene = Scene.find(params[:id])
  end

  def scene_params
    params.require(:scene).permit(:content, :project_id, :summary, :editor_id, :p1, :p2)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/decisions/create.html.erb
<h1>Decisions#create</h1>
<p>Find me in app/views/decisions/create.html.erb</p>

app/views/decisions/destroy.html.erb
<h1>Decisions#destroy</h1>
<p>Find me in app/views/decisions/destroy.html.erb</p>

app/views/decisions/edit.html.erb
<h1>Decisions#edit</h1>
<p>Find me in app/views/decisions/edit.html.erb</p>

app/views/decisions/index.html.erb
<h1>Decisions#index</h1>
<p>Find me in app/views/decisions/index.html.erb</p>

app/views/decisions/new.html.erb
<h1>Decisions#new</h1>
<p>Find me in app/views/decisions/new.html.erb</p>

app/views/decisions/show.html.erb
<h1>Decisions#show</h1>
<p>Find me in app/views/decisions/show.html.erb</p>

app/views/decisions/update.html.erb
<h1>Decisions#update</h1>
<p>Find me in app/views/decisions/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Project Cronus</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body onload="init()">
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="logo"><%= image_tag "title.png", class:"logoImg" %>
<div><a href="#projects"><%= image_tag "down.png", class:"arrow"%></a></div>
<!-- <h1>ronus</h1> --></div>
<div><h2 id="projects">Projects</h2>
<!-- <div class="searchBar center">Search stories here</div> --></div>
<div class="container_proj">
  <% @projects.each do |p| %>
      <% if(p.published) %>
       <div class="projects">
          <div class="coverPic"><%= image_tag "realIcon.png", class:"coverImg"%></div>
          <div class="projInfo">
            <h3><%= link_to p.name, project_path(p) %></h3><br>
            <p class="floatRight">by <%= p.user.username %></p>
          </div>
      </div>
      <% end %>

      <% end %>
</div>
<div class="footer center", style="color: black">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos perferendis facilis deleniti cumque, amet, ab sint vero laboriosam accusamus, dolor doloribus fugit adipisci? Atque in expedita laboriosam ipsa, dolor similique.</div>
<script type="text/javascript">
  document.getElementById("home").style.display = "none";
  document.getElementById("homeIcn").style.display = "none";
</script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script>
$(document).ready(function(){
  // Add smooth scrolling to all links
  $("a").on('click', function(event) {

    // Make sure this.hash has a value before overriding default behavior
    if (this.hash !== "") {
      // Prevent default anchor click behavior
      event.preventDefault();

      // Store hash
      var hash = this.hash;

      // Using jQuery's animate() method to add smooth page scroll
      // The optional number (800) specifies the number of milliseconds it takes to scroll to the specified area
      $('html, body').animate({
        scrollTop: $(hash).offset().top
      }, 300, function(){

        // Add hash (#) to URL when done scrolling (default click behavior)
        window.location.hash = hash;
      });
    } // End if
  });
});
</script>

app/views/pages/profile.html.erb
<h2>My Projects</h2>
<div class='projects'>
  <div class="coverPic"><div class="coverPic"><%= image_tag "realIcon.png", class:"coverImg"%></div></div>
  <div class="projInfo">
    <br><br>
    <p class="btn floatRight"><%= link_to "+ Add a Story", new_project_path %></p>
  </div>
</div>

<% @projects.each do |p| %>
  <div class='projects'>
    <div class="coverPic"><div class="coverPic"><%= image_tag "realIcon.png", class:"coverImg"%></div></div>

    <div class="projInfo">
      <h3 class="floatleft"><%= link_to p.name, project_path(p) %></h3><br><br>

      <div class="dropdown">
        <p class="btn floatRight dropbtn">Edit</p>
        <div class="dropdown-content">
          <%= link_to "Edit content", project_owner_work_path(p) %>
          <%= link_to "Edit name and description", edit_project_path(p) %>
        </div>
      </div>

      <% if(!p.published) %>
        <div class="floatleft" id="btn-publish">
          <button class="btn" id='publish' onclick="publish(<%= p.id %>)">Publish</button>
        </div>
      <% else %>
        <div class="floatleft" id="btn-bring-offline">
          <button class="btn" id='bring-offline' onclick="bringOffline(<%= p.id %>)">Bring Offline</button>
        </div>
      <% end %>

      <p class="btn floatRight"><%= link_to "Delete", project_path(p), method: :delete, data: {confirm: "Are you sure you want to delete this?"} %></p>
    </div>
  </div>
<% end %>

<script type="text/javascript" id="code">
  function publish(projectId){
    $.ajax({
      type: "PATCH",
      url:"/projects/"+projectId,
      data: {project:{
        project_id: projectId,
        published: true
      }},
      success: function(data, textStatus, jqXHR){
        console.log("eihei!");
        document.getElementById("btn-publish").innerHTML="Published";
      },
      error: function(jqXHR, textStatus, errorThrown){
        console.log("faaaaaaa");
      }
    });
  }

  function bringOffline(projectId){
    $.ajax({
      type: "PATCH",
      url:"/projects/"+projectId,
      data: {project:{
        project_id: projectId,
        published: false
      }},
      success: function(data, textStatus, jqXHR){
        console.log("eihei!");
        document.getElementById("btn-bring-offline").innerHTML="Brought Offline";
      },
      error: function(jqXHR, textStatus, errorThrown){
        console.log("faaaaaaa");
      }
    });
  }
</script>

app/views/projects/create.html.erb
<h1>Projects#create</h1>
<p>Find me in app/views/projects/create.html.erb</p>

app/views/projects/destroy.html.erb
<h1>Projects#destroy</h1>
<p>Find me in app/views/projects/destroy.html.erb</p>

app/views/projects/edit.html.erb
<div class='container'>
  <h3>Edit Title/Description</h3>
  <div class="form-inputs">
      <%= form_for @project, method: "put"  do |f| %>
      <%= f.text_field :name , class: "new-proj", placeholder: @project.name%><br>
      <%= f.text_area :description, class: "new-proj", placeholder: @project.description %><br>
      <%= f.submit :class => "btn floatRight" %>
    <% end %>
    </div>

app/views/projects/elaborate_scenes.html.erb
<div class="container">
  <%= link_to "<<Back to workspace", project_owner_work_path(@project, p),style:"text-decoration:underline" %> <br><br>
<h3><%= @project.name %></h3>


<% @project.scenes.each do |s| %>
  <% if s.editor_id == -1 %>
    <li>Starting Chapter | <%= link_to "Elaborate", edit_project_scene_path(@project, s) %></li>
  <% end %>
<% end %>

<% @project.scenes.each do |s| %>
  <% if s.editor_id != -1 %>
    <li><%= s.summary %> | <%= link_to "Elaborate", edit_project_scene_path(@project, s) %></li>
  <% end %>
<% end %>
</div>

app/views/projects/new.html.erb
<div class='container'>
  <div class="form-inputs">
    <h3>New Project</h3>
    <div class="new-project">
    <%= form_for @project do |f| %>
      <%= f.text_field :name , class: "new-proj", placeholder: "Title", required: true %><br>
      <%= f.text_area :description, class: "new-proj", placeholder: "Description" %><br>
      <%= f.submit :class => "btn floatRight" %>
    <% end %>
    </div>
  </div>
</div>

app/views/projects/play.html.erb
<h2 style="background-color: transparent; text-align:left;margin-left: 30%;margin-top: 10px;margin-right: 20%"><%= @project.name %></h2>
<div class="container", style="margin-top:10px; overflow:auto;">
    <% @project.scenes.each do |s| %>
      <% if s.editor_id == -1 %>
        <p><%= s.content%></p>

        <% s.decisions.each do |d|%>
          <% s.project.scenes.each do |ss| %>
            <% if ss.editor_id == d.next_editor_id %>
              <div style="text-decoration:underline;">
                <p>
                  <%= link_to d.description, project_scene_path(@project, ss) %>
                </p>
              </div>
            <% end %>
          <% end %>
        <% end %>

      <% end %>
    <% end %>
</div>

app/views/projects/show.html.erb
<div class="storyContainer">
  <div class="coverPic storyPic"><%= image_tag "realIcon.png", class:"storyImg"%></div>
    <div class="storyInfo">
      <h2 style="text-align:left;"><%= @project.name %></h2>
        <p><strong>by <%= @project.user.username %></strong></p>
        <p><%= @project.description %></p>
        <p class="storyBtn btn"><%= link_to "Start Reading", project_play_path(@project) %></p>
    </div>
</div>

app/views/projects/update.html.erb
<h1>Projects#update</h1>
<p>Find me in app/views/projects/update.html.erb</p>

app/views/scenes/create.html.erb
<div class="container">
  <h2>Add Scene</h2>
  <p>Find me in app/views/scenes/create.html.erb</p>
</div>

app/views/scenes/delete.html.erb
<h1>Scenes#delete</h1>
<p>Find me in app/views/scenes/delete.html.erb</p>

app/views/scenes/edit.html.erb
<div class="container">

  <%= link_to "See all chapters", project_elaborate_scenes_path(@scene.project),style:"text-decoration:underline" %>

  <h3><%= @scene.summary %></h3>
  <p class="floatRight", style="color: #4f4f4f; font-size:5px;">*Note: Chapter name will not be displayed to readers</p><br>

 <!--  <div>
    <h3>Content preview: </h3>

      <div class="no-text-overflow">
        <p id="contentPreview" class="proj-display show-line-break"></p>
      </div>
  </div> -->




<script type="text/javascript" id="code">
  var projectId = <%= @scene.project.id %>;
  var sceneId = <%= @scene.id %>;
  function init(){
    $.ajax({
      type: "GET",
      url:"/projects/"+projectId+"/scenes/"+sceneId+"/json",
      success: function(data, textStatus, jqXHR){
        console.log(data);
        document.getElementById("sceneContent").value = data.scene.content;
        document.getElementById("contentPreview").innerHTML = data.scene.content;
      },
      error: function(jqXHR, textStatus, errorThrown){
        console.log("faaaaaaa");
      }
    });
  };

  function editScene(projectId, sceneId, scene){
    $.ajax({
      type: "PATCH",
      url:"/projects/"+projectId+"/scenes/"+sceneId,
      data: scene,
      success: function(data, textStatus, jqXHR){
        console.log("eihei");
      },
      error: function(jqXHR, textStatus, errorThrown){
        console.log("faaaaaaa");
      }
    });
  };

  function save(){
    let newContent = document.getElementById("sceneContent").value;
    let newScene = {
      scene: {
        content: newContent
      }
    };
    editScene(projectId, sceneId, newScene);
  };

  function load(){
    $.ajax({
      type: "GET",
      url:"/projects/"+projectId+"/scenes/"+sceneId+"/json",
      success: function(data, textStatus, jqXHR){
        console.log(data);
        document.getElementById("sceneContent").value = data.scene.content;
        document.getElementById("contentPreview").innerHTML = data.scene.content;
      },
      error: function(jqXHR, textStatus, errorThrown){
        console.log("faaaaaaa");
      }
    });
  };


</script>

<div>
  <h4>Chapter content:</h4>
  <textarea id="sceneContent" style="width:100%;height:300px">
  </textarea>
  <div class="floatRight">
    <button onclick="save()">Save chapter content</button>
    <button onclick="load()">Load chapter content</button>
</div>
  <div>
    <br><br><br>
    <h4>Decisions: </h4>
    <br>
    <% @scene.decisions.each do |d| %>
      <p style="font-size: 15pt;">· <%= d.description %></p>
    <% end %>
  </div>
</div>

app/views/scenes/new.html.erb
<div class="container">
  <h2>New Scene</h2>

  <%= form_for [@p, @scene] do |f| %>
    <%= f.text_area :summary, placeholder: "Scene title", required: true %><br>
    <%= f.text_area :content, rows: 15, cols: 50, required: true %>
    <%= f.hidden_field :project_id, value: @p.id %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.submit %>
  <% end %>
</div>

app/views/scenes/show.html.erb
<h2 style="background-color: transparent; text-align:left;margin-left: 30%;margin-top: 10px;"><%= @scene.project.name %></h2>
<div class="container", style="margin-top:10px; overflow:auto;">
  <div>
    <p><%= @scene.content %></p>

    <% @scene.decisions.each do |d|%>
        <% @scene.project.scenes.each do |s| %>
          <% if s.editor_id == d.next_editor_id %>
            <div style="text-decoration:underline;">
              <p>
                <%= link_to d.description, project_scene_path(@scene.project, s) %>
              </p>
            </div>
          <% end %>
        <% end %>
    <% end %>
  </div>
</div>

app/views/scenes/update.html.erb
<h1>Scenes#update</h1>
<p>Find me in app/views/scenes/update.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "realIcon.png", class: "img-responsive",id:"homeIcn" %>
    <%= link_to "ronus", "/", class: "nav-link", id:"home" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <%= current_user.username %>   <%= image_tag "userIcon.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My Projects", "/profile", class: "dropdown-item" %>
            <%= link_to "Edit My Info", "/users/edit", class: "dropdown-item" %>
            <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign in", new_user_session_path, class: "nav-link", style:"color:white" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>